/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './core/routes/__root'
import { Route as UsersRouteImport } from './core/routes/users/route'

// Create/Update Routes

const UsersRouteRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./core/routes/users/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/users': typeof UsersRouteRoute
}

export interface FileRoutesByTo {
  '/users': typeof UsersRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/users': typeof UsersRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/users'
  id: '__root__' | '/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  UsersRouteRoute: typeof UsersRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  UsersRouteRoute: UsersRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/users"
      ]
    },
    "/users": {
      "filePath": "users/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
